{% set name = "argbash" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/matejak/argbash/archive/refs/tags/{{ version }}.tar.gz
  sha256: a749518116624e0ff1f71c9eadfd28e8580c3be6534446fbcd421ab6a67d453e

build:
  skip: true  # [win]
  number: 0
  script: |
    set -euxo pipefail
    cd resources
    make install PREFIX=$PREFIX ROOT=/


requirements:
  host:
    - make
    - autoconf >=2.63
  run:
    - autoconf >=2.63

test:
  commands:
    - argbash --version

about:
  home: https://github.com/matejak/argbash
  summary: 'Bash argument parsing code generator'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
